name: flappy
description: "A new Flutter project."
publish_to: 'none' # 防止意外发布到 pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

# 项目依赖
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flame: ^1.10.1  # 添加 Flame 依赖

# 开发依赖
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

# Flutter 特定配置
flutter:
  uses-material-design: true

  # 添加资源
  assets:
    - assets/images/bird.png
    - assets/images/background.png

  # 添加自定义字体
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
